name: lab_clinicas_core
description: "A new Flutter package project."
version: 0.0.1
environment:
  sdk: ">=3.4.4 <4.0.0"
  flutter: ">=1.17.0"
dependencies:
  flutter:
    sdk: flutter
  signals_flutter: ^5.5.0
  top_snackbar_flutter: ^3.1.0
  asyncstate: ^2.1.1-dev.1
  loading_animation_widget: ^1.2.1
  dio: ^5.7.0
  shared_preferences: ^2.3.2
  flutter_getit: ^2.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
